version: "3"

services:
  microservice:
    image: saber-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 800:800
    env_file:
      - .env
    volumes:
      - ./volumes/:/backend/volumes/